# Generated by Django 3.0.2 on 2020-01-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Friend_Class', '0002_auto_20200108_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hometown',
        ),
    ]
